version: 2
jobs:
  development:
    docker:
      - image: circleci/node:latest
    steps:
      - run:
          name: which branch
          command: echo ${CIRCLE_BRANCH}
      - run:
          name: The GitHub username of the user who triggered the build.
          command: echo ${CIRCLE_USERNAME}
